[evidence]
site_url = "https://eleanor-shen.github.io/project0/index.html"
archive_url = "https://web.archive.org/web/20260916201017/https://eleanor-shen.github.io/project0/index.html"
backlink_urls = [
  "https://hkitchener29.github.io/p0/",
  "https://sasha-gonch.github.io/CSCI40/",
]